services:
    projeto:
        build: backend
        volumes:
            - type: bind
              source: ./data
              target: /app/data
        container_name: ProjetoIBMEC
        image: ProjetoIBMEC
        networks:
            projeto_ibmec_net:
                aliases:
                    - projeto_ibmec
            default:
                aliases:
                    - projeto_ibmec
        restart: unless-stopped

networks:
    projeto_ibmec_net:
        name: projeto_ibmec_net
